<x-app-layout>
 <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800">Gunggungan</h2></x-slot>
 @php($rp=fn($n)=>'Rp '.number_format($n,0,',','.')) @php($num=fn($n)=>number_format($n,0,',','.'))
 <style>.overflow-hidden table { width:100% !important; border-collapse:collapse; }</style>
 <div class="py-8"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-5">
  <section class="rounded-xl p-6 shadow-sm" style="background:#172033;color:#fff"><p class="text-xs font-semibold uppercase tracking-widest" style="color:#93c5fd">Transaksi {{ \Carbon\Carbon::create($year,$month,1)->translatedFormat('F Y') }}</p><p class="mt-3 text-3xl font-bold" style="color:#fff">{{ $rp($totalNilai) }}</p><p class="mt-1 text-sm" style="color:#cbd5e1">{{ number_format($totalNota,0,',','.') }} nota selesai · kompilasi ledger</p></section>
  <form method="GET" class="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4 shadow-sm"><div><label class="mb-1 block text-xs font-medium text-gray-600">Tanggal tertentu</label><select name="tanggal" class="rounded-lg border-gray-300 text-sm"><option value="">Semua tanggal</option>@foreach(range(1,31) as $n)<option value="{{ $n }}" @selected($day===$n)>{{ $n }}</option>@endforeach</select></div><div><label class="mb-1 block text-xs font-medium text-gray-600">Bulan</label><select name="bulan" class="rounded-lg border-gray-300 text-sm">@foreach(range(1,12) as $n)<option value="{{ $n }}" @selected($month===$n)>{{ \Carbon\Carbon::create($year,$n,1)->translatedFormat('F') }}</option>@endforeach</select></div><div><label class="mb-1 block text-xs font-medium text-gray-600">Tahun</label><input type="number" name="tahun" min="2020" max="2100" value="{{ $year }}" class="w-24 rounded-lg border-gray-300 text-sm"></div><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">Cari</button><a href="{{ route('akuntansi.gunggungan') }}" class="px-2 py-2 text-sm font-semibold text-gray-600 hover:text-indigo-700">Reset</a></form>
  <section class="rounded-xl border bg-white p-3 shadow-sm"><div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px;margin-bottom:8px;text-align:center;font-size:11px;font-weight:700;color:#64748b"><span>MIN</span><span>SEN</span><span>SEL</span><span>RAB</span><span>KAM</span><span>JUM</span><span>SAB</span></div><div style="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px">@foreach ($calendar as $calendarDay)
      @if (! $calendarDay->isCurrent)<div style="min-height:92px;border-radius:8px;background:#f8fafc;padding:10px;color:#94a3b8"><p style="margin:0;font-size:12px">{{ $calendarDay->day }}</p></div>
      @else <a href="{{ route('akuntansi.gunggungan',['tanggal'=>$calendarDay->day,'bulan'=>$month,'tahun'=>$year]) }}" style="display:block;min-height:92px;border:1px solid {{ $selectedDate===$calendarDay->date?'#6366f1':($calendarDay->jumlah_nota===0?'#fecaca':'#e2e8f0') }};border-radius:8px;padding:10px;text-decoration:none;background:{{ $calendarDay->jumlah_nota===0?'#fef2f2':'#ffffff' }};box-shadow:0 1px 2px rgba(15,23,42,.06)"><p style="margin:0;font-size:12px;color:{{ $calendarDay->jumlah_nota===0?'#ef4444':'#64748b' }}">{{ $calendarDay->day }}</p><p style="margin:10px 0 0;font-size:14px;font-weight:700;color:{{ $calendarDay->jumlah_nota===0?'#dc2626':'#111827' }}">{{ $rp($calendarDay->total) }}</p><p style="margin:4px 0 0;font-size:12px;color:{{ $calendarDay->jumlah_nota===0?'#ef4444':'#64748b' }}">{{ $calendarDay->jumlah_nota }} nota</p></a>
      @endif
    @endforeach</div></section>
  <section class="overflow-hidden rounded-xl border bg-white"><div class="border-b px-5 py-4 font-semibold">{{ $selectedDate?'Transaksi '.\Carbon\Carbon::parse($selectedDate)->translatedFormat('d F Y'):'Seluruh transaksi' }}</div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead style="background:#eef2ff;color:#4f46e5"><tr><th style="padding:12px 20px;text-align:left;font-size:12px">Tanggal</th><th style="padding:12px 20px;text-align:left;font-size:12px">No. Nota</th><th style="padding:12px 20px;text-align:left;font-size:12px">Customer</th><th style="padding:12px 20px;text-align:right;font-size:12px">DPP</th><th style="padding:12px 20px;text-align:right;font-size:12px">DPP Nilai Lain</th><th style="padding:12px 20px;text-align:right;font-size:12px">PPN 12%</th><th style="padding:12px 20px;text-align:right;font-size:12px">Nilai Nota</th></tr></thead><tbody class="divide-y">@forelse($orders as $order)<tr><td class="px-5 py-3">{{ \Carbon\Carbon::parse($order->TglOrder)->format('d-m-Y') }}</td><td class="px-5 py-3 font-semibold text-indigo-700">{{ $order->NoOrder }}</td><td class="px-5 py-3">{{ $order->customer?->NmCust??'-' }}</td><td class="px-5 py-3 text-right">{{ $num($order->dpp) }}</td><td class="px-5 py-3 text-right">{{ $num($order->dpp_nilai_lain) }}</td><td class="px-5 py-3 text-right">{{ $num($order->ppn) }}</td><td class="px-5 py-3 text-right font-semibold">{{ $num($order->total) }}</td></tr>@empty<tr><td colspan="7" class="px-5 py-10 text-center text-gray-500">Belum ada data.</td></tr>@endforelse</tbody></table></div><div class="border-t px-5 py-3">{{ $orders->links() }}</div></section>
 </div></div>
</x-app-layout>
