<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800">Buku Piutang Customer</h2></x-slot>
    @php($money = fn ($value) => number_format((float) $value, 0, ',', '.'))
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-4 px-4 sm:px-6 lg:px-8">
        <section class="rounded-xl border bg-white p-5 shadow-sm"><form method="GET" class="flex flex-wrap items-end gap-3"><label class="text-sm text-gray-700">Dari<input type="date" name="dari" value="{{ $dari }}" class="mt-1 block rounded-lg border-gray-300 text-sm"></label><label class="text-sm text-gray-700">Sampai<input type="date" name="sampai" value="{{ $sampai }}" class="mt-1 block rounded-lg border-gray-300 text-sm"></label><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Tampilkan</button></form><p class="mt-3 text-sm text-gray-500">Sumber laporan adalah jurnal akun Piutang Dagang (11102). Karena itu saldo buku piutang selalu dapat dicocokkan dengan Buku Besar.</p></section>
        <section class="overflow-hidden rounded-xl border bg-white shadow-sm"><div class="border-b px-5 py-4"><h3 class="font-semibold text-gray-900">Rekap Piutang per Customer</h3></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-indigo-50 text-xs uppercase tracking-wide text-indigo-700"><tr><th class="px-5 py-3 text-left">Customer</th><th class="px-5 py-3 text-right">Saldo Awal</th><th class="px-5 py-3 text-right">Penjualan Kredit</th><th class="px-5 py-3 text-right">Pelunasan / Pengurang</th><th class="px-5 py-3 text-right">Sisa Piutang</th></tr></thead><tbody class="divide-y">@forelse($rows as $row)<tr><td class="px-5 py-3"><p class="font-medium text-gray-900">{{ $row->nama }}</p><p class="text-xs text-gray-500">{{ $row->kode }}</p></td><td class="px-5 py-3 text-right">{{ $money($row->opening) }}</td><td class="px-5 py-3 text-right">{{ $money($row->penjualan) }}</td><td class="px-5 py-3 text-right text-emerald-700">{{ $money($row->pelunasan) }}</td><td class="px-5 py-3 text-right font-semibold {{ $row->ending > 0 ? 'text-amber-700' : '' }}">{{ $money($row->ending) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-gray-500">Belum ada mutasi piutang pada periode ini.</td></tr>@endforelse</tbody><tfoot class="bg-gray-50 font-semibold"><tr><td class="px-5 py-3">Total</td><td class="px-5 py-3 text-right">{{ $money($rows->sum('opening')) }}</td><td class="px-5 py-3 text-right">{{ $money($rows->sum('penjualan')) }}</td><td class="px-5 py-3 text-right">{{ $money($rows->sum('pelunasan')) }}</td><td class="px-5 py-3 text-right">{{ $money($rows->sum('ending')) }}</td></tr></tfoot></table></div></section>
        <section class="overflow-hidden rounded-xl border bg-white shadow-sm"><div class="border-b px-5 py-4"><h3 class="font-semibold text-gray-900">Rincian Mutasi Piutang</h3></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-xs uppercase tracking-wide text-gray-600"><tr><th class="px-5 py-3 text-left">Tanggal</th><th class="px-5 py-3 text-left">Bukti</th><th class="px-5 py-3 text-left">Customer</th><th class="px-5 py-3 text-left">Keterangan</th><th class="px-5 py-3 text-right">Debet</th><th class="px-5 py-3 text-right">Kredit</th></tr></thead><tbody class="divide-y">@forelse($details as $entry)<tr><td class="px-5 py-3">{{ \Carbon\Carbon::parse($entry->TgTrans)->format('d-m-Y') }}</td><td class="px-5 py-3 font-medium text-indigo-700">{{ $entry->Bukti }}</td><td class="px-5 py-3">{{ $names[$entry->KdBantu] ?? $entry->KdBantu }}</td><td class="px-5 py-3 text-gray-600">{{ $entry->KetMT }}</td><td class="px-5 py-3 text-right">{{ $entry->Debet > 0 ? $money($entry->Debet) : '-' }}</td><td class="px-5 py-3 text-right">{{ $entry->Kredit > 0 ? $money($entry->Kredit) : '-' }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-gray-500">Tidak ada mutasi pada periode ini.</td></tr>@endforelse</tbody></table></div></section>
    </div></div>
</x-app-layout>
