<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800">Laporan Pembelian</h2></x-slot>
    @php($money = fn ($value) => number_format((float) $value, 0, ',', '.'))
    @php($label = ['bahan_baku' => 'Bahan Baku', 'bahan_penolong' => 'Bahan Penolong', 'aset' => 'Aset / Disusutkan', 'biaya' => 'Biaya'])
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-4 px-4 sm:px-6 lg:px-8">
        <section class="rounded-xl border bg-white p-5 shadow-sm"><form method="GET" class="flex flex-wrap items-end gap-3"><label class="text-sm text-gray-700">Dari<input type="date" name="from" value="{{ $from }}" class="mt-1 block rounded-lg border-gray-300 text-sm"></label><label class="text-sm text-gray-700">Sampai<input type="date" name="to" value="{{ $to }}" class="mt-1 block rounded-lg border-gray-300 text-sm"></label><label class="text-sm text-gray-700">Klasifikasi<select name="klasifikasi" class="mt-1 block rounded-lg border-gray-300 text-sm"><option value="">Semua</option>@foreach($label as $key => $value)<option value="{{ $key }}" @selected($classification === $key)>{{ $value }}</option>@endforeach</select></label><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Tampilkan</button></form><p class="mt-3 text-sm text-gray-500">Nilai pada tabel adalah DPP / harga sebelum PPN, sesuai format rekap pembelian Januari.</p></section>
        <section class="grid gap-3 sm:grid-cols-4">@foreach($label as $key => $value)<div class="rounded-xl border bg-white p-4 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $value }}</p><p class="mt-2 text-lg font-bold text-gray-900">{{ $money($totals[$key] ?? 0) }}</p></div>@endforeach</section>
        <section class="overflow-hidden rounded-xl border bg-white shadow-sm"><div class="border-b px-5 py-4"><h3 class="font-semibold text-gray-900">Rincian Pembelian</h3></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-indigo-50 text-xs uppercase tracking-wide text-indigo-700"><tr><th class="px-4 py-3 text-left">Tanggal</th><th class="px-4 py-3 text-left">Supplier</th><th class="px-4 py-3 text-left">No. SJ / Faktur</th><th class="px-4 py-3 text-left">Bahan / Barang</th><th class="px-4 py-3 text-left">Klasifikasi</th><th class="px-4 py-3 text-right">Qty</th><th class="px-4 py-3 text-right">Harga</th><th class="px-4 py-3 text-right">Total Sebelum Pajak</th></tr></thead><tbody class="divide-y">@forelse($lines as $line)<tr><td class="px-4 py-3">{{ $line->purchase->tanggal->format('d-m-Y') }}</td><td class="px-4 py-3">{{ $line->purchase->supplier->nama }}</td><td class="px-4 py-3 font-medium text-indigo-700">{{ $line->purchase->nomor_bukti }}</td><td class="px-4 py-3">{{ $line->deskripsi }}</td><td class="px-4 py-3">{{ $label[$line->klasifikasi] }}</td><td class="px-4 py-3 text-right">{{ number_format($line->qty, 3, ',', '.') }} {{ $line->satuan }}</td><td class="px-4 py-3 text-right">{{ $money($line->harga_satuan) }}</td><td class="px-4 py-3 text-right font-semibold">{{ $money($line->subtotal) }}</td></tr>@empty<tr><td colspan="8" class="px-5 py-10 text-center text-gray-500">Belum ada pembelian dengan rincian item pada periode ini.</td></tr>@endforelse</tbody><tfoot class="bg-gray-50 font-semibold"><tr><td colspan="7" class="px-4 py-3 text-right">Total DPP</td><td class="px-4 py-3 text-right">{{ $money($lines->sum('subtotal')) }}</td></tr></tfoot></table></div></section>
    </div></div>
</x-app-layout>
